### ISSUE TITLE
Windows installed success, but nothing response by click

### ISSUE THREAD

**Issue by litaipo** [vran-dev/PrettyZoo#101]
## PrettyZoo 版本
version: v1.0.0
type: msi / exe

## 操作系统版本
windows 10

## 本地 JDK 版本
11.0.10

## 问题描述
点击启动图标无响应，打包后自行启动也抛异常

## 日志信息
```java
```
点击无反应不知道哪里看日志，下边是自己打包运行的日志：
Unrecognized option: --module-path
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by vran-dev** [comment]
安装路径是否包含了中文或者其他 unicode 字符？可以尝试安装在全英文目录再启动试试

**Comment by JackLiMEM** [comment]
> 安装路径是否包含了中文或者其他 unicode 字符？可以尝试安装在全英文目录再启动试试

我卸载重新安装了，用默认安装路径是可以的，之前我安装的路径是D:\Program Files

**Comment by gy1234** [comment]
卸载重新安装了，用默认安装路径：C:\Users\xxx\AppData\Local\prettyZoo\prettyZoo.exe
还是点击无反应，看不到任何错误

PrettyZoo 版本：
version: v1.9.4
type: msi / exe

操作系统版本
windows 10专业版

本地 JDK 版本
11.0.12

问题描述
点击启动图标无响应

**Comment by gy1234** [comment]
> > 安装路径是否包含了中文或者其他 unicode 字符？可以尝试安装在全英文目录再启动试试
> 
> 我卸载重新安装了，用默认安装路径是可以的，之前我安装的路径是D:\Program Files

查看错误日志找到原因了，解决方案是手动屏蔽Assistive Technology
1. 在当前用户目录下找到文件（C:\Users\Xxxx\.accessibility.properties）
2. 手动注释掉#assistive_technologies=com.sun.java.accessibility.AccessBridge
3. 再重新启动prettyZoo.exe，最后还不行就卸载重装，还是不行就再从控制台看错误堆栈吧
说说我猜测原因：Assistive Technology可能是之前JDK8遗留的
贴下控制台打印错误堆栈信息：
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at java.base/sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.awt.AWTError: Assistive Technology not found: com.sun.java.accessibility.AccessBridge
        at java.desktop/java.awt.Toolkit.newAWTError(Unknown Source)
        at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Unknown Source)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Unknown Source)
        at java.desktop/java.awt.Taskbar.isTaskbarSupported(Unknown Source)
        at java.desktop/java.awt.Taskbar.getTaskbar(Unknown Source)
        at app.main@1.9.4/cc.cc1234.PrettyZooApplication.lambda$initIconImage$0(Unknown Source)
        at java.base/java.util.Optional.ifPresent(Unknown Source)
        at app.main@1.9.4/cc.cc1234.PrettyZooApplication.initIconImage(Unknown Source)
        at app.main@1.9.4/cc.cc1234.PrettyZooApplication.main(Unknown Source)
        ... 11 more
Caused by: java.lang.ClassNotFoundException: com.sun.java.accessibility.AccessBridge
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        ... 29 more

**Comment by vran-dev** [comment]
@gy1234  hello, 我发布了新版  [v1.9.5](https://github.com/vran-dev/PrettyZoo/releases/tag/v1.9.5) ，使用 java17 构建，也许能解决这个问题

**Comment by ztyzbb** [comment]
1.9.5似乎能用了

**Comment by vran-dev** [comment]
Please use [V1.9.5](https://github.com/vran-dev/PrettyZoo/releases/tag/v1.9.5) if you have same problem
