### ISSUE TITLE
Access the zk through [IP:PORT], but can’t access it through by [domain name:PORT]

### ISSUE THREAD

**Issue by jkl0898** [vran-dev/PrettyZoo#144]
1. 版本
v1.7.0

2. 问题
可以通过IP:PORT 的方式访问， 但是无法通过域名:PORT 方式访问

3. 期望
支持IP:PORT ， 并同时支持域名:PORT 方式访问.

**Comment by vran-dev** [comment]
@jkl0898 

我本体验证是可以的， 你可以先在你本地验证一下域名是否能够被 DNS 解析成功

**Comment by jkl0898** [comment]
不好意思，刚看到消息。验证了本地域名可以被DNS 解析， 但是连接不上

**Comment by jkl0898** [comment]
![image](https://user-images.githubusercontent.com/14175165/116038361-f1b14380-a69b-11eb-8169-8e99a240e06e.png)

**Comment by jkl0898** [comment]
![Uploading image.png…]()

**Comment by jkl0898** [comment]
Windows 版本的

**Comment by vran-dev** [comment]
如果 Host 解析正常的话，另一种可能就是端口的问题了

**Comment by jkl0898** [comment]
> 如果 Host 解析正常的话，另一种可能就是端口的问题了

你好。我使用CMD 命令行工具执行telnet ${hostName} ${Port} 进行测试。
测试可以通过主机名和端口连接成功。

**Comment by jkl0898** [comment]
> > > 如果 Host 解析正常的话，另一种可能就是端口的问题了
> > 
> > 
> > 你好。我使用CMD 命令行工具执行telnet ${hostName} ${Port} 进行测试。
> > 测试可以通过主机名和端口连接成功。
> 
> 如果方便的化可以提供以下完整 host （出于隐私考虑可以修改混淆） 以及 zookeeper 的版本， 你也可以观察 {USER.HOME}/prettyZoo/log 下的日志定位问题。

你好。host 是内网的， zookeeper 的版本是zookeeper-3.5.6。
我在安装目录没有找到log 目录（C盘用户目录下也没找到）， windows 版本的，请问如何打开日志？
![image](https://user-images.githubusercontent.com/14175165/118232174-ba0a1000-b47f-11eb-91ef-7468a08b7ee1.png)

**Comment by vran-dev** [comment]
@jkl0898 

在用户目录下（user.home）, 有一个 `.prettyZoo` 文件夹，里面有对应的日志信息

你也可以尝试一下升级版本  https://github.com/vran-dev/PrettyZoo/releases

**Comment by jkl0898** [comment]
[2021-05-24 at 10:08:40 CST] [ERROR] app.main@1.7.0/cc.cc1234.app.controller.ServerViewController.lambda$onConnect$17(Unknown Source) - connect server error
java.util.concurrent.CompletionException: java.lang.IllegalStateException: connect xxx:30181 failed
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalStateException: connect xxx:30181 failed
	at cc.cc1234.client.curator.CuratorZookeeperConnectionFactory.createAsync(Unknown Source) ~[specificationImpl.main:?]
	at cc.cc1234.core.zookeeper.factory.ZookeeperFactory.lambda$create$0(Unknown Source) ~[core.main:?]
	at cc.cc1234.core.zookeeper.entity.Zookeeper.<init>(Unknown Source) ~[core.main:?]
	at cc.cc1234.core.zookeeper.factory.ZookeeperFactory.create(Unknown Source) ~[core.main:?]
	at cc.cc1234.core.zookeeper.service.ZookeeperDomainService.connect(Unknown Source) ~[core.main:?]
	at cc.cc1234.app.facade.PrettyZooFacade.lambda$connect$0(Unknown Source) ~[app.main:?]
	... 7 more

你好，错误日志如上。xxx:30181 经过脱敏处理

**Comment by jkl0898** [comment]
> @jkl0898
> 
> 在用户目录下（user.home）, 有一个 `.prettyZoo` 文件夹，里面有对应的日志信息
> 
> 你也可以尝试一下升级版本 https://github.com/vran-dev/PrettyZoo/releases

尝试升级了新版本也无法连接。报错信息是一样的。

**Comment by vran-dev** [comment]
@jkl0898 

我使用了同样的版本 zookeeper 验证了不是版本的问题，从错误来看 dns 解析也是正常的。

有实际验证过 dns 解析的 IP 是 zookeeper 所在机器吗？
