### ISSUE TITLE
在Windows中安装prettyZoo，连接linux虚拟机中的zk，显示连接异常，倒是连接不上，其他客户端都能连上

### ISSUE THREAD

**Issue by xiangwei520** [vran-dev/PrettyZoo#170]
![测试图片](https://user-images.githubusercontent.com/63486338/117755406-b9d6fe00-b24e-11eb-9ba6-3e974463bb08.png)
## 连接linux虚拟机中的zk，显示连接异常
在Windows中安装prettyZoo，连接linux虚拟机中的zk，显示连接异常，倒是连接不上，其他客户端都能连上!!!

version: 所有版本

platform: 
- [ ] windows

package type: platform default

OS version: Windows10 / Ubuntu1804

description:

what happened ? your expected ?

log:

> you can find log in {user.home}/.prettyZoo/log

**Comment by vran-dev** [comment]
hello， 你可以查看一下 {user.home}/.prettyZoo/log 下的日志，如果还是无法定位问题的话可以将内容贴上来。

对了， 你可以再提供一下你的 zookeeper 版本吗？

**Comment by xiangwei520** [comment]
你好：
&nbsp; &nbsp; &nbsp;测试截图和连接日志见附件！


&nbsp; &nbsp; &nbsp;linux虚拟机上安装zookeeper版本：apache-zookeeper-3.5.9-bin，截图如下:
&nbsp; &nbsp; &nbsp;

&nbsp; &nbsp; &nbsp;windows机器 ping linux虚拟机可以ping通，网络是通的，截图如下：
&nbsp; &nbsp; &nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vran-dev/PrettyZoo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月11日(星期二) 中午11:54
***@***.***&gt;;
抄送:&nbsp;"鱼戈 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [vran-dev/PrettyZoo] 在Windows中安装prettyZoo，连接linux虚拟机中的zk，显示连接异常，倒是连接不上，其他客户端都能连上 (#170)





 
hello， 你可以查看一下 {user.home}/.prettyZoo/log 下的日志，如果还是无法定位问题的话可以将内容贴上来。
 
对了， 你可以再提供一下你的 zookeeper 版本吗？

**Comment by xiangwei520** [comment]
***@***.***/org.apache.curator.framework.imps.CuratorFrameworkImpl.start(Unknown&nbsp;Source)&nbsp;-&nbsp;Starting
***@***.******@***.***
***@***.***/org.apache.curator.framework.imps.CuratorFrameworkImpl.start(Unknown&nbsp;Source)&nbsp;-&nbsp;Default&nbsp;schema
***@***.***/org.apache.zookeeper.ClientCnxn$SendThread.logStartConnect(Unknown&nbsp;Source)&nbsp;-&nbsp;Opening&nbsp;socket&nbsp;connection&nbsp;to&nbsp;server&nbsp;192.168.109.100/192.168.109.100:2181.&nbsp;Will&nbsp;not&nbsp;attempt&nbsp;to&nbsp;authenticate&nbsp;using&nbsp;SASL&nbsp;(unknown&nbsp;error)
***@***.***/org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(Unknown&nbsp;Source)&nbsp;-&nbsp;backgroundOperationsLoop&nbsp;exiting
***@***.***/org.apache.zookeeper.ClientCnxn$EventThread.run(Unknown&nbsp;Source)&nbsp;-&nbsp;EventThread&nbsp;shut&nbsp;down
***@***.***/org.apache.zookeeper.ZooKeeper.close(Unknown&nbsp;Source)&nbsp;-&nbsp;Session:&nbsp;0x0&nbsp;closed
***@***.***/cc.cc1234.app.controller.NodeViewController.switchServer(Unknown&nbsp;Source)&nbsp;-&nbsp;switch&nbsp;server&nbsp;192.168.109.100:2181&nbsp;failed:&nbsp;
java.lang.IllegalStateException:&nbsp;连接超时
at&nbsp;cc.cc1234.client.curator.CuratorZookeeperConnectionFactory.create(Unknown&nbsp;Source)&nbsp;~[infrastructure.main:?]
at&nbsp;cc.cc1234.domain.zookeeper.factory.ZookeeperFactory.lambda$create$0(Unknown&nbsp;Source)&nbsp;~[domain.main:?]
at&nbsp;cc.cc1234.domain.zookeeper.entity.Zookeeper.<init&gt;(Unknown&nbsp;Source)&nbsp;~[domain.main:?]
at&nbsp;cc.cc1234.domain.zookeeper.factory.ZookeeperFactory.create(Unknown&nbsp;Source)&nbsp;~[domain.main:?]
at&nbsp;cc.cc1234.domain.zookeeper.service.ZookeeperDomainService.connect(Unknown&nbsp;Source)&nbsp;~[domain.main:?]
at&nbsp;cc.cc1234.app.facade.PrettyZooFacade.connect(Unknown&nbsp;Source)&nbsp;~[app.main:?]
at&nbsp;cc.cc1234.app.controller.NodeViewController.switchServer(Unknown&nbsp;Source)&nbsp;~[app.main:?]
at&nbsp;cc.cc1234.app.controller.NodeViewController.show(Unknown&nbsp;Source)&nbsp;~[app.main:?]
at&nbsp;cc.cc1234.app.controller.ServerViewController.lambda$onConnect$14(Unknown&nbsp;Source)&nbsp;~[app.main:?]
at&nbsp;cc.cc1234.app.fp.Try.of(Unknown&nbsp;Source)&nbsp;~[app.main:?]
at&nbsp;cc.cc1234.app.controller.ServerViewController.onConnect(Unknown&nbsp;Source)&nbsp;~[app.main:?]
at&nbsp;cc.cc1234.app.controller.ServerViewController.lambda$showServerInfoView$0(Unknown&nbsp;Source)&nbsp;~[app.main:?]
at&nbsp;com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;com.sun.javafx.event.EventUtil.fireEventImpl(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;com.sun.javafx.event.EventUtil.fireEvent(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;javafx.event.Event.fireEvent(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;javafx.scene.Scene$ClickGenerator.postProcess(Unknown&nbsp;Source)&nbsp;~[javafx.graphics:?]
at&nbsp;javafx.scene.Scene$MouseHandler.process(Unknown&nbsp;Source)&nbsp;~[javafx.graphics:?]
at&nbsp;javafx.scene.Scene.processMouseEvent(Unknown&nbsp;Source)&nbsp;~[javafx.graphics:?]
at&nbsp;javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown&nbsp;Source)&nbsp;~[javafx.graphics:?]
at&nbsp;com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown&nbsp;Source)&nbsp;~[javafx.graphics:?]
at&nbsp;com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown&nbsp;Source)&nbsp;~[javafx.graphics:?]
at&nbsp;java.security.AccessController.doPrivileged(Unknown&nbsp;Source)&nbsp;~[?:?]
at&nbsp;com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown&nbsp;Source)&nbsp;~[javafx.graphics:?]
at&nbsp;com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown&nbsp;Source)&nbsp;~[javafx.graphics:?]
at&nbsp;com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown&nbsp;Source)&nbsp;~[javafx.graphics:?]
at&nbsp;com.sun.glass.ui.View.handleMouseEvent(Unknown&nbsp;Source)&nbsp;~[javafx.graphics:?]
at&nbsp;com.sun.glass.ui.View.notifyMouse(Unknown&nbsp;Source)&nbsp;~[javafx.graphics:?]
at&nbsp;com.sun.glass.ui.win.WinApplication._runLoop(Native&nbsp;Method)&nbsp;~[javafx.graphics:?]
at&nbsp;com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown&nbsp;Source)&nbsp;~[javafx.graphics:?]
at&nbsp;java.lang.Thread.run(Unknown&nbsp;Source)&nbsp;[?:?]
***@***.***/cc.cc1234.app.controller.ServerViewController.lambda$onConnect$15(Unknown&nbsp;Source)&nbsp;-&nbsp;connect&nbsp;server&nbsp;error
java.lang.IllegalStateException:&nbsp;connect&nbsp;to&nbsp;192.168.109.100:2181&nbsp;failed
at&nbsp;cc.cc1234.app.controller.NodeViewController.switchServer(Unknown&nbsp;Source)&nbsp;~[app.main:?]
at&nbsp;cc.cc1234.app.controller.NodeViewController.show(Unknown&nbsp;Source)&nbsp;~[app.main:?]
at&nbsp;cc.cc1234.app.controller.ServerViewController.lambda$onConnect$14(Unknown&nbsp;Source)&nbsp;~[app.main:?]
at&nbsp;cc.cc1234.app.fp.Try.of(Unknown&nbsp;Source)&nbsp;~[app.main:?]
at&nbsp;cc.cc1234.app.controller.ServerViewController.onConnect(Unknown&nbsp;Source)&nbsp;~[app.main:?]
at&nbsp;cc.cc1234.app.controller.ServerViewController.lambda$showServerInfoView$0(Unknown&nbsp;Source)&nbsp;~[app.main:?]
at&nbsp;com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;com.sun.javafx.event.EventUtil.fireEventImpl(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;com.sun.javafx.event.EventUtil.fireEvent(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;javafx.event.Event.fireEvent(Unknown&nbsp;Source)&nbsp;~[javafx.base:?]
at&nbsp;javafx.scene.Scene$ClickGenerator.postProcess(Unknown&nbsp;Source)&nbsp;~[javafx.graphics:?]
at&nbsp;javafx.scene.Scene$MouseHandler.process(Unknown&nbsp;Source)&nbsp;~[javafx.graphics:?]
at&nbsp;javafx.scene.Scene.processMouseEvent(Unknown&nbsp;Source)&nbsp;~[javafx.graphics:?]
at&nbsp;javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown&nbsp;Source)&nbsp;~[javafx.graphics:?]
at&nbsp;com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown&nbsp;Source)&nbsp;~[javafx.graphics:?]
at&nbsp;com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown&nbsp;Source)&nbsp;~[javafx.graphics:?]
at&nbsp;java.security.AccessController.doPrivileged(Unknown&nbsp;Source)&nbsp;~[?:?]
at&nbsp;com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown&nbsp;Source)&nbsp;~[javafx.graphics:?]
at&nbsp;com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown&nbsp;Source)&nbsp;~[javafx.graphics:?]
at&nbsp;com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown&nbsp;Source)&nbsp;~[javafx.graphics:?]
at&nbsp;com.sun.glass.ui.View.handleMouseEvent(Unknown&nbsp;Source)&nbsp;~[javafx.graphics:?]
at&nbsp;com.sun.glass.ui.View.notifyMouse(Unknown&nbsp;Source)&nbsp;~[javafx.graphics:?]
at&nbsp;com.sun.glass.ui.win.WinApplication._runLoop(Native&nbsp;Method)&nbsp;~[javafx.graphics:?]
at&nbsp;com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown&nbsp;Source)&nbsp;~[javafx.graphics:?]
at&nbsp;java.lang.Thread.run(Unknown&nbsp;Source)&nbsp;[?:?]
Caused&nbsp;by:&nbsp;java.lang.IllegalStateException:&nbsp;连接超时
at&nbsp;cc.cc1234.client.curator.CuratorZookeeperConnectionFactory.create(Unknown&nbsp;Source)&nbsp;~[infrastructure.main:?]
at&nbsp;cc.cc1234.domain.zookeeper.factory.ZookeeperFactory.lambda$create$0(Unknown&nbsp;Source)&nbsp;~[domain.main:?]
at&nbsp;cc.cc1234.domain.zookeeper.entity.Zookeeper.<init&gt;(Unknown&nbsp;Source)&nbsp;~[domain.main:?]
at&nbsp;cc.cc1234.domain.zookeeper.factory.ZookeeperFactory.create(Unknown&nbsp;Source)&nbsp;~[domain.main:?]
at&nbsp;cc.cc1234.domain.zookeeper.service.ZookeeperDomainService.connect(Unknown&nbsp;Source)&nbsp;~[domain.main:?]
at&nbsp;cc.cc1234.app.facade.PrettyZooFacade.connect(Unknown&nbsp;Source)&nbsp;~[app.main:?]
...&nbsp;36&nbsp;more




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "鱼戈 🎈"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月11日(星期二) 中午12:24
***@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [vran-dev/PrettyZoo] 在Windows中安装prettyZoo，连接linux虚拟机中的zk，显示连接异常，倒是连接不上，其他客户端都能连上 (#170)



你好：
&nbsp; &nbsp; &nbsp;测试截图和连接日志见附件！


&nbsp; &nbsp; &nbsp;linux虚拟机上安装zookeeper版本：apache-zookeeper-3.5.9-bin，截图如下:
&nbsp; &nbsp; &nbsp;

&nbsp; &nbsp; &nbsp;windows机器 ping linux虚拟机可以ping通，网络是通的，截图如下：
&nbsp; &nbsp; &nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "vran-dev/PrettyZoo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月11日(星期二) 中午11:54
***@***.***&gt;;
抄送:&nbsp;"鱼戈 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [vran-dev/PrettyZoo] 在Windows中安装prettyZoo，连接linux虚拟机中的zk，显示连接异常，倒是连接不上，其他客户端都能连上 (#170)





 
hello， 你可以查看一下 {user.home}/.prettyZoo/log 下的日志，如果还是无法定位问题的话可以将内容贴上来。
 
对了， 你可以再提供一下你的 zookeeper 版本吗？

**Comment by xiangwei520** [comment]
你好：
&nbsp; &nbsp; &nbsp; 已经可以正常连接了&nbsp; 谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "鱼戈 🎈"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月11日(星期二) 下午2:11
***@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [vran-dev/PrettyZoo] 在Windows中安装prettyZoo，连接linux虚拟机中的zk，显示连接异常，倒是连接不上，其他客户端都能连上 (#170)



[2021-05-11 at 12:18:11 CST] [INFO ] ***@***.***/org.apache.curator.framework.imps.CuratorFrameworkImpl.start(Unknown Source) - Starting
[2021-05-11 at 12:18:11 CST] [INFO ] ***@***.***/org.apache.zookeeper.ZooKeeper.<init&gt;(Unknown Source) - Initiating client connection, connectString=192.168.109.100:2181 sessionTimeout=60000 ***@***.***
[2021-05-11 at 12:18:11 CST] [INFO ] ***@***.***/org.apache.curator.framework.imps.CuratorFrameworkImpl.start(Unknown Source) - Default schema
[2021-05-11 at 12:18:11 CST] [INFO ] ***@***.***/org.apache.zookeeper.ClientCnxn$SendThread.logStartConnect(Unknown Source) - Opening socket connection to server 192.168.109.100/192.168.109.100:2181. Will not attempt to authenticate using SASL (unknown error)
[2021-05-11 at 12:18:16 CST] [INFO ] ***@***.***/org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(Unknown Source) - backgroundOperationsLoop exiting
[2021-05-11 at 12:18:32 CST] [INFO ] ***@***.***/org.apache.zookeeper.ClientCnxn$EventThread.run(Unknown Source) - EventThread shut down
[2021-05-11 at 12:18:32 CST] [INFO ] ***@***.***/org.apache.zookeeper.ZooKeeper.close(Unknown Source) - Session: 0x0 closed
[2021-05-11 at 12:18:32 CST] [ERROR] ***@***.***/cc.cc1234.app.controller.NodeViewController.switchServer(Unknown Source) - switch server 192.168.109.100:2181 failed: 
java.lang.IllegalStateException: 连接超时
at cc.cc1234.client.curator.CuratorZookeeperConnectionFactory.create(Unknown Source) ~[infrastructure.main:?]
at cc.cc1234.domain.zookeeper.factory.ZookeeperFactory.lambda$create$0(Unknown Source) ~[domain.main:?]
at cc.cc1234.domain.zookeeper.entity.Zookeeper.<init&gt;(Unknown Source) ~[domain.main:?]
at cc.cc1234.domain.zookeeper.factory.ZookeeperFactory.create(Unknown Source) ~[domain.main:?]
at cc.cc1234.domain.zookeeper.service.ZookeeperDomainService.connect(Unknown Source) ~[domain.main:?]
at cc.cc1234.app.facade.PrettyZooFacade.connect(Unknown Source) ~[app.main:?]
at cc.cc1234.app.controller.NodeViewController.switchServer(Unknown Source) ~[app.main:?]
at cc.cc1234.app.controller.NodeViewController.show(Unknown Source) ~[app.main:?]
at cc.cc1234.app.controller.ServerViewController.lambda$onConnect$14(Unknown Source) ~[app.main:?]
at cc.cc1234.app.fp.Try.of(Unknown Source) ~[app.main:?]
at cc.cc1234.app.controller.ServerViewController.onConnect(Unknown Source) ~[app.main:?]
at cc.cc1234.app.controller.ServerViewController.lambda$showServerInfoView$0(Unknown Source) ~[app.main:?]
at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source) ~[javafx.base:?]
at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source) ~[javafx.base:?]
at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source) ~[javafx.base:?]
at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source) ~[javafx.base:?]
at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source) ~[javafx.base:?]
at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source) ~[javafx.base:?]
at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source) ~[javafx.base:?]
at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source) ~[javafx.base:?]
at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source) ~[javafx.base:?]
at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source) ~[javafx.base:?]
at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source) ~[javafx.base:?]
at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source) ~[javafx.base:?]
at com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source) ~[javafx.base:?]
at com.sun.javafx.event.EventUtil.fireEvent(Unknown Source) ~[javafx.base:?]
at javafx.event.Event.fireEvent(Unknown Source) ~[javafx.base:?]
at javafx.scene.Scene$ClickGenerator.postProcess(Unknown Source) ~[javafx.graphics:?]
at javafx.scene.Scene$MouseHandler.process(Unknown Source) ~[javafx.graphics:?]
at javafx.scene.Scene.processMouseEvent(Unknown Source) ~[javafx.graphics:?]
at javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source) ~[javafx.graphics:?]
at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source) ~[javafx.graphics:?]
at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source) ~[javafx.graphics:?]
at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source) ~[javafx.graphics:?]
at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source) ~[javafx.graphics:?]
at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source) ~[javafx.graphics:?]
at com.sun.glass.ui.View.handleMouseEvent(Unknown Source) ~[javafx.graphics:?]
at com.sun.glass.ui.View.notifyMouse(Unknown Source) ~[javafx.graphics:?]
at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[javafx.graphics:?]
at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source) ~[javafx.graphics:?]
at java.lang.Thread.run(Unknown Source) [?:?]
[2021-05-11 at 12:18:32 CST] [ERROR] ***@***.***/cc.cc1234.app.controller.ServerViewController.lambda$onConnect$15(Unknown Source) - connect server error
java.lang.IllegalStateException: connect to 192.168.109.100:2181 failed
at cc.cc1234.app.controller.NodeViewController.switchServer(Unknown Source) ~[app.main:?]
at cc.cc1234.app.controller.NodeViewController.show(Unknown Source) ~[app.main:?]
at cc.cc1234.app.controller.ServerViewController.lambda$onConnect$14(Unknown Source) ~[app.main:?]
at cc.cc1234.app.fp.Try.of(Unknown Source) ~[app.main:?]
at cc.cc1234.app.controller.ServerViewController.onConnect(Unknown Source) ~[app.main:?]
at cc.cc1234.app.controller.ServerViewController.lambda$showServerInfoView$0(Unknown Source) ~[app.main:?]
at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source) ~[javafx.base:?]
at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source) ~[javafx.base:?]
at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source) ~[javafx.base:?]
at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source) ~[javafx.base:?]
at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source) ~[javafx.base:?]
at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source) ~[javafx.base:?]
at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source) ~[javafx.base:?]
at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source) ~[javafx.base:?]
at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source) ~[javafx.base:?]
at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source) ~[javafx.base:?]
at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source) ~[javafx.base:?]
at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source) ~[javafx.base:?]
at com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source) ~[javafx.base:?]
at com.sun.javafx.event.EventUtil.fireEvent(Unknown Source) ~[javafx.base:?]
at javafx.event.Event.fireEvent(Unknown Source) ~[javafx.base:?]
at javafx.scene.Scene$ClickGenerator.postProcess(Unknown Source) ~[javafx.graphics:?]
at javafx.scene.Scene$MouseHandler.process(Unknown Source) ~[javafx.graphics:?]
at javafx.scene.Scene.processMouseEvent(Unknown Source) ~[javafx.graphics:?]
at javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source) ~[javafx.graphics:?]
at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source) ~[javafx.graphics:?]
at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source) ~[javafx.graphics:?]
at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source) ~[javafx.graphics:?]
at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source) ~[javafx.graphics:?]
at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source) ~[javafx.graphics:?]
at com.sun.glass.ui.View.handleMouseEvent(Unknown Source) ~[javafx.graphics:?]
at com.sun.glass.ui.View.notifyMouse(Unknown Source) ~[javafx.graphics:?]
at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[javafx.graphics:?]
at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source) ~[javafx.graphics:?]
at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalStateException: 连接超时
at cc.cc1234.client.curator.CuratorZookeeperConnectionFactory.create(Unknown Source) ~[infrastructure.main:?]
at cc.cc1234.domain.zookeeper.factory.ZookeeperFactory.lambda$create$0(Unknown Source) ~[domain.main:?]
at cc.cc1234.domain.zookeeper.entity.Zookeeper.<init&gt;(Unknown Source) ~[domain.main:?]
at cc.cc1234.domain.zookeeper.factory.ZookeeperFactory.create(Unknown Source) ~[domain.main:?]
at cc.cc1234.domain.zookeeper.service.ZookeeperDomainService.connect(Unknown Source) ~[domain.main:?]
at cc.cc1234.app.facade.PrettyZooFacade.connect(Unknown Source) ~[app.main:?]
... 36 more




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "鱼戈 🎈"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月11日(星期二) 中午12:24
***@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [vran-dev/PrettyZoo] 在Windows中安装prettyZoo，连接linux虚拟机中的zk，显示连接异常，倒是连接不上，其他客户端都能连上 (#170)



你好：
&nbsp; &nbsp; &nbsp;测试截图和连接日志见附件！


&nbsp; &nbsp; &nbsp;linux虚拟机上安装zookeeper版本：apache-zookeeper-3.5.9-bin，截图如下:
&nbsp; &nbsp; &nbsp;

&nbsp; &nbsp; &nbsp;windows机器 ping linux虚拟机可以ping通，网络是通的，截图如下：
&nbsp; &nbsp; &nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "vran-dev/PrettyZoo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月11日(星期二) 中午11:54
***@***.***&gt;;
抄送:&nbsp;"鱼戈 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [vran-dev/PrettyZoo] 在Windows中安装prettyZoo，连接linux虚拟机中的zk，显示连接异常，倒是连接不上，其他客户端都能连上 (#170)





 
hello， 你可以查看一下 {user.home}/.prettyZoo/log 下的日志，如果还是无法定位问题的话可以将内容贴上来。
 
对了， 你可以再提供一下你的 zookeeper 版本吗？

**Comment by vran-dev** [comment]
@xiangwei520 

ok, 如果方便的话可以描述一下你的 root cause，也许有人和你有同样的问题。

对了，从界面看你的版本比较老了，你可以尝试以下最新的版本（功能、ui 均有调整）

版本 release 地址：https://github.com/vran-dev/PrettyZoo/releases
