### ISSUE TITLE
get trouble when use SSH Tunne

### ISSUE THREAD

**Issue by fchange** [vran-dev/PrettyZoo#201]
## ISSUE

version: latest

platform: 

- [x] windows
- [ ] mac
- [ ] Linux

package type: platform default

OS version: Windows10

description:

when i use the SSH Tunne to connect remote zookeeper node, it shows a WARNING:

**java.net.BindException: Cannot assign requested address: bind**

**Comment by vran-dev** [comment]
could you offer error log to me ?
you can find it at /{user.home}/.prettyZoo/log directory

@fchange

**Comment by fchange** [comment]
```
[2021-07-09 at 11:28:00 CST] [INFO ] cc.c1234.merged.module@1.9.2/net.schmizz.sshj.transport.random.BouncyCastleRandom.<init>(Unknown Source) - Generating random seed from SecureRandom.
[2021-07-09 at 11:28:00 CST] [INFO ] cc.c1234.merged.module@1.9.2/net.schmizz.sshj.transport.TransportImpl.sendClientIdent(Unknown Source) - Client identity string: SSH-2.0-SSHJ_0.27.0
[2021-07-09 at 11:28:00 CST] [INFO ] cc.c1234.merged.module@1.9.2/net.schmizz.sshj.transport.TransportImpl.init(Unknown Source) - Server identity string: SSH-2.0-OpenSSH_7.4
[2021-07-09 at 11:28:01 CST] [ERROR] app.main@1.9.2/cc.cc1234.app.controller.ServerViewController.lambda$onConnect$18(Unknown Source) - connect server error
java.util.concurrent.CompletionException: java.lang.IllegalStateException: java.net.BindException: Cannot assign requested address: bind
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalStateException: java.net.BindException: Cannot assign requested address: bind
	at cc.cc1234.core.zookeeper.entity.SSHTunnel.create(Unknown Source) ~[core.main:?]
	at cc.cc1234.core.zookeeper.entity.Zookeeper.<init>(Unknown Source) ~[core.main:?]
	at cc.cc1234.core.zookeeper.factory.ZookeeperFactory.create(Unknown Source) ~[core.main:?]
	at cc.cc1234.core.zookeeper.service.ZookeeperDomainService.connect(Unknown Source) ~[core.main:?]
	at cc.cc1234.app.facade.PrettyZooFacade.lambda$connect$0(Unknown Source) ~[app.main:?]
	... 7 more
Caused by: java.net.BindException: Cannot assign requested address: bind
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Unknown Source) ~[?:?]
	at sun.nio.ch.Net.bind(Unknown Source) ~[?:?]
	at sun.nio.ch.NioSocketImpl.bind(Unknown Source) ~[?:?]
	at java.net.ServerSocket.bind(Unknown Source) ~[?:?]
	at java.net.ServerSocket.bind(Unknown Source) ~[?:?]
	at cc.cc1234.core.zookeeper.entity.SSHTunnel.create(Unknown Source) ~[core.main:?]
	at cc.cc1234.core.zookeeper.entity.Zookeeper.<init>(Unknown Source) ~[core.main:?]
	at cc.cc1234.core.zookeeper.factory.ZookeeperFactory.create(Unknown Source) ~[core.main:?]
	at cc.cc1234.core.zookeeper.service.ZookeeperDomainService.connect(Unknown Source) ~[core.main:?]
	at cc.cc1234.app.facade.PrettyZooFacade.lambda$connect$0(Unknown Source) ~[app.main:?]
	... 7 more
```

**Comment by vran-dev** [comment]
> ```
> [2021-07-09 at 11:28:00 CST] [INFO ] cc.c1234.merged.module@1.9.2/net.schmizz.sshj.transport.random.BouncyCastleRandom.<init>(Unknown Source) - Generating random seed from SecureRandom.
> [2021-07-09 at 11:28:00 CST] [INFO ] cc.c1234.merged.module@1.9.2/net.schmizz.sshj.transport.TransportImpl.sendClientIdent(Unknown Source) - Client identity string: SSH-2.0-SSHJ_0.27.0
> [2021-07-09 at 11:28:00 CST] [INFO ] cc.c1234.merged.module@1.9.2/net.schmizz.sshj.transport.TransportImpl.init(Unknown Source) - Server identity string: SSH-2.0-OpenSSH_7.4
> [2021-07-09 at 11:28:01 CST] [ERROR] app.main@1.9.2/cc.cc1234.app.controller.ServerViewController.lambda$onConnect$18(Unknown Source) - connect server error
> java.util.concurrent.CompletionException: java.lang.IllegalStateException: java.net.BindException: Cannot assign requested address: bind
> 	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
> 	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) [?:?]
> 	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?]
> 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:?]
> 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
> 	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
> 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
> 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
> Caused by: java.lang.IllegalStateException: java.net.BindException: Cannot assign requested address: bind
> 	at cc.cc1234.core.zookeeper.entity.SSHTunnel.create(Unknown Source) ~[core.main:?]
> 	at cc.cc1234.core.zookeeper.entity.Zookeeper.<init>(Unknown Source) ~[core.main:?]
> 	at cc.cc1234.core.zookeeper.factory.ZookeeperFactory.create(Unknown Source) ~[core.main:?]
> 	at cc.cc1234.core.zookeeper.service.ZookeeperDomainService.connect(Unknown Source) ~[core.main:?]
> 	at cc.cc1234.app.facade.PrettyZooFacade.lambda$connect$0(Unknown Source) ~[app.main:?]
> 	... 7 more
> Caused by: java.net.BindException: Cannot assign requested address: bind
> 	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
> 	at sun.nio.ch.Net.bind(Unknown Source) ~[?:?]
> 	at sun.nio.ch.Net.bind(Unknown Source) ~[?:?]
> 	at sun.nio.ch.NioSocketImpl.bind(Unknown Source) ~[?:?]
> 	at java.net.ServerSocket.bind(Unknown Source) ~[?:?]
> 	at java.net.ServerSocket.bind(Unknown Source) ~[?:?]
> 	at cc.cc1234.core.zookeeper.entity.SSHTunnel.create(Unknown Source) ~[core.main:?]
> 	at cc.cc1234.core.zookeeper.entity.Zookeeper.<init>(Unknown Source) ~[core.main:?]
> 	at cc.cc1234.core.zookeeper.factory.ZookeeperFactory.create(Unknown Source) ~[core.main:?]
> 	at cc.cc1234.core.zookeeper.service.ZookeeperDomainService.connect(Unknown Source) ~[core.main:?]
> 	at cc.cc1234.app.facade.PrettyZooFacade.lambda$connect$0(Unknown Source) ~[app.main:?]
> 	... 7 more
> ```

May be your port is used by another process

**Comment by fchange** [comment]
which Port？ local Port？ I don't know where to configurate it.
can you offer a picture shows how I  correctly fill in the parameters, the input box on the interface makes me confused.

also, the top input box can only be entered once, and then it becomes uneditable.

**Comment by vran-dev** [comment]
when you enable SSH-Tunnel, prettyZoo will use [zookeeper server:port] to create local proxy, so, you should change this port to avoid conflict.

![image](https://user-images.githubusercontent.com/12870335/125156953-c3bba580-e19a-11eb-9c1b-080f538235e9.png)

yes, you can't modify server and port after saved, but you can create a new server.

**Comment by fchange** [comment]
New problem, when I click "connect", there is a circle that keeps turning, but it has remained for a long time and the connection has not been completed. Attach the corresponding log
```
[2021-07-10 at 16:30:28 CST] [INFO ] cc.c1234.merged.module@1.9.2/net.schmizz.sshj.transport.random.BouncyCastleRandom.<init>(Unknown Source) - Generating random seed from SecureRandom.
[2021-07-10 at 16:30:28 CST] [INFO ] cc.c1234.merged.module@1.9.2/net.schmizz.sshj.transport.TransportImpl.sendClientIdent(Unknown Source) - Client identity string: SSH-2.0-SSHJ_0.27.0
[2021-07-10 at 16:30:28 CST] [INFO ] cc.c1234.merged.module@1.9.2/net.schmizz.sshj.transport.TransportImpl.init(Unknown Source) - Server identity string: SSH-2.0-OpenSSH_7.4
[2021-07-10 at 16:30:29 CST] [INFO ] cc.c1234.merged.module@1.9.2/net.schmizz.sshj.connection.channel.direct.LocalPortForwarder.listen(Unknown Source) - Listening on /127.0.0.1:2181
```

**Comment by vran-dev** [comment]
> New problem, when I click "connect", there is a circle that keeps turning, but it has remained for a long time and the connection has not been completed. Attach the corresponding log
> 
> ```
> [2021-07-10 at 16:30:28 CST] [INFO ] cc.c1234.merged.module@1.9.2/net.schmizz.sshj.transport.random.BouncyCastleRandom.<init>(Unknown Source) - Generating random seed from SecureRandom.
> [2021-07-10 at 16:30:28 CST] [INFO ] cc.c1234.merged.module@1.9.2/net.schmizz.sshj.transport.TransportImpl.sendClientIdent(Unknown Source) - Client identity string: SSH-2.0-SSHJ_0.27.0
> [2021-07-10 at 16:30:28 CST] [INFO ] cc.c1234.merged.module@1.9.2/net.schmizz.sshj.transport.TransportImpl.init(Unknown Source) - Server identity string: SSH-2.0-OpenSSH_7.4
> [2021-07-10 at 16:30:29 CST] [INFO ] cc.c1234.merged.module@1.9.2/net.schmizz.sshj.connection.channel.direct.LocalPortForwarder.listen(Unknown Source) - Listening on /127.0.0.1:2181
> ```

unfortunately, it's a bug...  I'll do my best to fix it and release at next version

thanks for your feedback

**Comment by fchange** [comment]
可以打个包吗大哥，我还不会打包

**Comment by vran-dev** [comment]
> 可以打个包吗大哥，我还不会打包

@fchange 

see [v1.9.3](https://github.com/vran-dev/PrettyZoo/releases/tag/v1.9.3)
