### ISSUE TITLE
prettyzoo 1.9.5 can't start in centos 7

### ISSUE THREAD

**Issue by zj452008181** [vran-dev/PrettyZoo#246]
## ISSUE

version: prettyzoo-1.9.5-1.x86_64.rpm

platform: linux  

package type: rpm

OS version: CentOS Linux release 7.9.2009

description:
can't start prettyzoo

log:
[root@host1 ~]# /opt/prettyzoo/bin/prettyZoo
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.lang.UnsupportedOperationException: Unable to open DISPLAY
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.<init>(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.Application.run(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.startup(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.startToolkit(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(Unknown Source)
	... 5 more

**Comment by vran-dev** [comment]
maybe you need to install `x11 window`

**Comment by vran-dev** [comment]
it's long time without your response, is your problem solved?

**Comment by zj452008181** [comment]
i don't install this,I think it's too bloated to install "x11 window" in my machine,maybe there's another, more elegant way like docker

**Comment by vran-dev** [comment]
thx
