### ISSUE TITLE
在win7 x64系统上, 分辨率1920*1080, 字体超级小

### ISSUE THREAD

**Issue by CrazyBeginner** [vran-dev/PrettyZoo#26]
![image](https://user-images.githubusercontent.com/5567096/101435117-bdd0be00-3946-11eb-9691-4169e09d769f.png)

**Comment by vran-dev** [comment]
感谢你的反馈和使用，我会在后续的版本中做优化和改进，请持续关注

**Comment by CrazyBeginner** [comment]
我想自己尝试修改字体大小，拉取了master的代码，导入idea， build成功，但是右键执行PrettyZooApplication的main方法， 报错：`Unnecessarily replacing a task that does not exist is not supported.  Use create() or register() directly instead.  You attempted to replace a task named 'PrettyZooApplication.main()', but there is no existing task with that name.
`
网上查了一下在.idea下的gradle.xml中添加一行代码`<option name="delegatedBuild" value="false" />`， 解决了。

继续右键执行， 报错：
`Exception in thread "WindowsNativeRunloopThread" java.lang.NoSuchMethodError: <init>
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.staticScreen_getScreens(Native Method)
	at javafx.graphics/com.sun.glass.ui.Screen.initScreens(Screen.java:412)
	at javafx.graphics/com.sun.glass.ui.Application.lambda$run$1(Application.java:152)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "WindowsNativeRunloopThread" java.lang.NoSuchMethodError: <init>
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.staticScreen_getScreens(Native Method)
	at javafx.graphics/com.sun.glass.ui.Screen.initScreens(Screen.java:412)
	at javafx.graphics/com.sun.glass.ui.Application.lambda$run$1(Application.java:152)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at javafx.graphics/com.sun.prism.d3d.D3DPipeline.getAdapterOrdinal(D3DPipeline.java:205)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.assignScreensAdapters(QuantumToolkit.java:695)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runToolkit(QuantumToolkit.java:313)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$startup$10(QuantumToolkit.java:258)
	at javafx.graphics/com.sun.glass.ui.Application.lambda$run$1(Application.java:153)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by vran-dev** [comment]
> 我想自己尝试修改字体大小，拉取了master的代码，导入idea， build成功，但是右键执行PrettyZooApplication的main方法， 报错：`Unnecessarily replacing a task that does not exist is not supported. Use create() or register() directly instead. You attempted to replace a task named 'PrettyZooApplication.main()', but there is no existing task with that name. `
> 网上查了一下在.idea下的gradle.xml中添加一行代码`<option name="delegatedBuild" value="false" />`， 解决了。
> 
> 继续右键执行， 报错：
> `Exception in thread "WindowsNativeRunloopThread" java.lang.NoSuchMethodError: <init> at javafx.graphics/com.sun.glass.ui.win.WinApplication.staticScreen_getScreens(Native Method) at javafx.graphics/com.sun.glass.ui.Screen.initScreens(Screen.java:412) at javafx.graphics/com.sun.glass.ui.Application.lambda$run$1(Application.java:152) at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method) at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174) at java.base/java.lang.Thread.run(Thread.java:834) Exception in thread "WindowsNativeRunloopThread" java.lang.NoSuchMethodError: <init> at javafx.graphics/com.sun.glass.ui.win.WinApplication.staticScreen_getScreens(Native Method) at javafx.graphics/com.sun.glass.ui.Screen.initScreens(Screen.java:412) at javafx.graphics/com.sun.glass.ui.Application.lambda$run$1(Application.java:152) at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method) at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174) at java.base/java.lang.Thread.run(Thread.java:834) Exception in thread "JavaFX Application Thread" java.lang.NullPointerException at javafx.graphics/com.sun.prism.d3d.D3DPipeline.getAdapterOrdinal(D3DPipeline.java:205) at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.assignScreensAdapters(QuantumToolkit.java:695) at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runToolkit(QuantumToolkit.java:313) at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$startup$10(QuantumToolkit.java:258) at javafx.graphics/com.sun.glass.ui.Application.lambda$run$1(Application.java:153) at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method) at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174) at java.base/java.lang.Thread.run(Thread.java:834)`

你使用的 JDK 是什么版本？ 切换到  jdk11 试试呢
