### ISSUE TITLE
Will not attempt to authenticate using SASL (unknown error)

### ISSUE THREAD

**Issue by shy20221121** [vran-dev/PrettyZoo#315]
[2023-02-22 at 17:36:05 CST] [INFO ] cc.c1234.merged.module@1.9.4/org.apache.curator.framework.imps.CuratorFrameworkImpl.start(Unknown Source) - Starting
[2023-02-22 at 17:36:05 CST] [INFO ] cc.c1234.merged.module@1.9.4/org.apache.zookeeper.ZooKeeper.<init>(Unknown Source) - Initiating client connection, connectString=10.128.53.237:2181 sessionTimeout=6000 watcher=org.apache.curator.ConnectionState@34d36b02
[2023-02-22 at 17:36:05 CST] [INFO ] cc.c1234.merged.module@1.9.4/org.apache.zookeeper.ClientCnxn$SendThread.logStartConnect(Unknown Source) - Opening socket connection to server 10.128.53.237/10.128.53.237:2181. Will not attempt to authenticate using SASL (unknown error)
[2023-02-22 at 17:36:05 CST] [INFO ] cc.c1234.merged.module@1.9.4/org.apache.curator.framework.imps.CuratorFrameworkImpl.start(Unknown Source) - Default schema
[2023-02-22 at 17:36:08 CST] [INFO ] cc.c1234.merged.module@1.9.4/org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(Unknown Source) - backgroundOperationsLoop exiting
[2023-02-22 at 17:36:11 CST] [INFO ] cc.c1234.merged.module@1.9.4/org.apache.zookeeper.ZooKeeper.close(Unknown Source) - Session: 0x0 closed
[2023-02-22 at 17:36:11 CST] [INFO ] cc.c1234.merged.module@1.9.4/org.apache.zookeeper.ClientCnxn$EventThread.run(Unknown Source) - EventThread shut down
[2023-02-22 at 17:36:11 CST] [ERROR] app.main@1.9.4/cc.cc1234.app.controller.ServerViewController.connectErrorCallback(Unknown Source) - connect server error
java.util.concurrent.CompletionException: java.lang.IllegalStateException: connect 10.128.53.237:2181 failed
 at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
 at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) [?:?]
 at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?]
 at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:?]
 at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
 at java.util.concurrent.ForkJoinPool$WorkQueue.topLevel

===============================================================================

telnet 10.128.53.237 2181 is ok in terminal.

but connet 10.128.53.237:2181 is failed in PrettyZoo.

**Comment by vran-dev** [comment]
could you show me your `zoo.cfg`?

**Comment by shy20221121** [comment]
> could you show me your `zoo.cfg`?

Hi, thanks for your reply ！this problem has been resolved ，
Because the prettyzoo take precedence use IPv6 protocol to connect network due to my vpn client still not support IPv6 to cause.
Solution: 
1, Open "prettyZoo.cfg"
2, New add "JVM option" java-options=-Djava.net.preferIPv4Stack=true。
3, Restart PrettyZoo

**Comment by vran-dev** [comment]
you can also try to use `zookeeper.properties` to configure it, prettyZoo will load it to `System.properties` when start
 
![image](https://user-images.githubusercontent.com/12870335/222170244-6cc8f35a-2ec0-424a-816e-910802b93345.png)

![image](https://user-images.githubusercontent.com/12870335/222170050-5118fd6b-197a-4e63-bae7-2cb4b6d68c71.png)

**Comment by shy20221121** [comment]
> you can also try to use `zookeeper.properties` to configure it, prettyZoo will load it to `System.properties` when start
> 
> ![image](https://user-images.githubusercontent.com/12870335/222170244-6cc8f35a-2ec0-424a-816e-910802b93345.png)
> 
> ![image](https://user-images.githubusercontent.com/12870335/222170050-5118fd6b-197a-4e63-bae7-2cb4b6d68c71.png)

Good, i will try this method.
