### ISSUE TITLE
java.lang.IllegalStateException: connect failed

### ISSUE THREAD

**Issue by wongfang728** [vran-dev/PrettyZoo#342]
java.util.concurrent.CompletionException: java.lang.IllegalStateException: connect zk-dev.xxx.com:2181 failed
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalStateException: connect zk-dev.xxx.com:2181 failed
	at cc.cc1234.client.curator.CuratorZookeeperConnectionFactory.createAsync(Unknown Source) ~[specificationImpl.main:?]
	at cc.cc1234.core.zookeeper.factory.ZookeeperFactory.lambda$create$0(Unknown Source) ~[core.main:?]
	at cc.cc1234.core.zookeeper.entity.Zookeeper.<init>(Unknown Source) ~[core.main:?]
	at cc.cc1234.core.zookeeper.factory.ZookeeperFactory.create(Unknown Source) ~[core.main:?]
	at cc.cc1234.core.zookeeper.service.ZookeeperDomainService.connect(Unknown Source) ~[core.main:?]
	at cc.cc1234.app.facade.PrettyZooFacade.lambda$connect$0(Unknown Source) ~[app.main:?]
	... 7 more

**Comment by wongfang728** [comment]
telnet是可以的

**Comment by wongfang728** [comment]
CuratorZookeeperConnectionFactory  的createAsync方法，` if (!client.blockUntilConnected(3, TimeUnit.SECONDS)) {
                client.close();
                throw new IllegalStateException("connect " + params.getUrl() + " failed");
            }`

**Comment by wongfang728** [comment]
这个不能改成配置化吗

**Comment by wongfang728** [comment]
实际原因是3.6.x以后的dns反解析问题，希望增加多一点配置避免这个问题，目前按照[https://www.cnblogs.com/kendoziyu/p/16035842.html](url)增加hosts方式解决，不是很友好
