### ISSUE TITLE
我java的dubbo服务可以连接上。idea插件zookeeper也能连接上。不知道为什么这个工具连接不上

### ISSUE THREAD

**Issue by 15526441465** [vran-dev/PrettyZoo#344]
[2023-08-14 at 22:17:01 HKT] [ERROR] app.main@2.1.1/cc.cc1234.app.controller.ServerViewController.connectErrorCallback(Unknown Source) - connect server error
java.util.concurrent.CompletionException: java.lang.IllegalStateException: connect 192.168.66.100:2181 failed
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalStateException: connect 192.168.66.100:2181 failed
	at cc.cc1234.client.curator.CuratorZookeeperConnectionFactory.createAsync(Unknown Source) ~[specificationImpl.main:?]
	at cc.cc1234.core.zookeeper.factory.ZookeeperFactory.lambda$create$0(Unknown Source) ~[core.main:?]
	at cc.cc1234.core.zookeeper.entity.Zookeeper.<init>(Unknown Source) ~[core.main:?]
	at cc.cc1234.core.zookeeper.factory.ZookeeperFactory.create(Unknown Source) ~[core.main:?]
	at cc.cc1234.core.zookeeper.service.ZookeeperDomainService.connect(Unknown Source) ~[core.main:?]
	at cc.cc1234.app.facade.PrettyZooFacade.lambda$connect$0(Unknown Source) ~[app.main:?]
	... 7 more

**Comment by 15526441465** [comment]
![3](https://github.com/vran-dev/PrettyZoo/assets/63545873/dee61cfb-df4e-499b-8a88-5c60ed1dfee3)
配置如下
